### ISSUE TITLE
Registration endpoints are not working

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_shaid_maids#3]
Steps to reproduce

POST `/maids/0/appids/register` with the body
```JSON
{
	"ids":"153465456"
}
```

Stack:

```
016-09-16T14:13:42.076Z mnem1t5nqd2y/1474035209117/1/- ERROR	act	root$       	OUT		method:register,model:appids,service:maids	8	{id:d3f0752b-600a-4165-b963-327e253a79f0,method:register,model:appids,service:maids,user:{id:7,email:scott@livi	PRIOR;(hk7pntmc9tey)	(bcry59atj7cn)	-	seneca: Action method:register,model:appids,service:maids failed: req is not defined.	act_execute	{id:x6jv1c5knxg2/9bi2ochmy3n5,gate:false,ungate:true,desc:null,time:{start:1474035222072},message:req is not de	ReferenceError: req is not defined
    at Seneca.<anonymous> (/usr/src/app/app/appids/appid_seneca.js:30:112)
    at Array.done (/usr/src/app/node_modules/seneca/seneca.js:1172:22)
    at validate_action_message (/usr/src/app/node_modules/seneca/seneca.js:1504:19)
    at Object.execute_action [as fn] (/usr/src/app/node_modules/seneca/seneca.js:1115:7)
    at Immediate.<anonymous> (/usr/src/app/node_modules/seneca/node_modules/gate-executor/gate-executor.js:136:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
2016-09-16T14:13:42.077Z mnem1t5nqd2y/1474035209117/1/- ERROR	act	root$       	OUT		method:register,model:appids,service:maids	12	{id:d3f0752b-600a-4165-b963-327e253a79f0,method:register,model:appids,service:maids,user:{id:7,email:scott@livi	ENTRY	(hk7pntmc9tey)	-	seneca: Action method:register,model:appids,service:maids failed: req is not defined.	act_execute	{id:x6jv1c5knxg2/9bi2ochmy3n5,gate:false,ungate:true,desc:null,time:{start:1474035222072},message:req is not de	ReferenceError: req is not defined
    at Seneca.<anonymous> (/usr/src/app/app/appids/appid_seneca.js:30:112)
    at Array.done (/usr/src/app/node_modules/seneca/seneca.js:1172:22)
    at validate_action_message (/usr/src/app/node_modules/seneca/seneca.js:1504:19)
    at Object.execute_action [as fn] (/usr/src/app/node_modules/seneca/seneca.js:1115:7)
    at Immediate.<anonymous> (/usr/src/app/node_modules/seneca/node_modules/gate-executor/gate-executor.js:136:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by ssmereka** [comment]
Fixed in 3ca9de031609535beb898b543f03b90d4cf936ef
